name: Docker Image to AWS ECR
run-name: ${{github.actor}}


on:
    push:
      branches:
        - master


permissions:
 id-token: write
 contents: read #This is required for actions/checkout@v2


jobs:
    generate-s3-url:
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: back
      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set up AWS credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            role-to-assume: arn:aws:iam::534108746974:role/test-image-bkt-role
            aws-region: "us-east-2"

        - name: Install dependencies
          run: npm install

        - name: Generate upload URL
          run: node s3.js

    Docker-Image:
        name: Docker Image Build and Push to ECR
        needs: generate-s3-url
        runs-on: ubuntu-latest
        defaults:
          run:
           working-directory: .

        steps:
            - name: Source code checkout
              uses: actions/checkout@v4

            # Allow role to access AWS console
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: arn:aws:iam::534108746974:role/Docker-S3-role
                aws-region: us-east-1

             # Hello from AWS: WhoAmI
            - name: Sts GetCallerIdentity
              run: |
                aws sts get-caller-identity


            - name: Login to Amazon ECR Public
              id: login-ecr-public
              uses: aws-actions/amazon-ecr-login@v2
              with:
                registry-type: public

            - name: Build, tag, and push docker image to Amazon ECR Public
              env:
                REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
                REGISTRY_ALIAS: a2e3r5u9
                REPOSITORY: s3loader
                IMAGE_TAG: ${{ github.sha }}
              run: |
                docker build -t $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG .
                docker push $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG

            - name: Set output tag
              id: set-tag
              run: echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV

    deploy:
        needs: Docker-Image
        runs-on: self-hosted
        steps:
          - name: Pull image from docker hub
            run:  docker pull public.ecr.aws/a2e3r5u9/s3loader:969c412384e945cd3448f41d66f11f4519054d49
          - name: Stop running container/image
            run:  docker stop s3loader || true
          - name: Delete old container
            run: docker rm -f s3loader
          - name: Run docker container
            run:  docker run -d -p 8080:8080 --name s3loader public.ecr.aws/a2e3r5u9/s3loader:${{ env.IMAGE_TAG }}

