name: Generate S3 Upload URL

on:
  push:
    branches:
      - master

permissions:
 id-token: write
 contents: read #This is required for actions/checkout@v2



jobs:
  generate-url:
    runs-on: ubuntu-latest
    defaults:
      run:
         working-directory: back
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::534108746974:role/test-image-bkt-role
          aws-region: "us-east-2"

      - name: Install dependencies
        run: npm install

      - name: Generate upload URL
        run: node s3.js
