name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS credentials from IAM Role
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: arn:aws:iam::534108746974:role/test-image-bkt-role
        aws-region: "us-east-2"

#     - name: Use Node.js
#       uses: actions/setup-node@v3
#       with:
#         node-version: '18.x'

#     - run: npm ci

#     - run: npm test

#     - name: Lint with ESLint
#       run: npm run lint

#   deploy:
#     needs: build
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2

#     - name: Configure AWS credentials from IAM Role
#       uses: aws-actions/configure-aws-credentials@v3
#       with:
#         role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
#         aws-region: "us-east-2"

#     - name: Deploy to S3
#       run: |
#         aws s3 cp ./build s3://$S3_BUCKET_NAME --recursive
